### ISSUE TITLE
PlayFab EditorExtensions: Caught an error:Invalid JSON string

### ISSUE THREAD

**Issue by Hugodzl** [PlayFab/UnityEditorExtensions#125]
Hi, I get that issue multiple times a day and once I get it the only thing I can do to "fix it" is to restart Unity completely. 
I get that error when I try to log in with a player account in my game but also sometimes when I open up the PlayFab Editor Extension window. 
 
![image](https://user-images.githubusercontent.com/25936579/87580082-e957c100-c6a4-11ea-9c5a-cc61192f597b.png)
[Editor.log](https://github.com/PlayFab/UnityEditorExtensions/files/4927160/Editor.log)

**Comment by toddbellMSFT** [comment]
Can you clarify a few comments on your repro steps?

1.) At first you mention "I try to log in in with a player account in my game."
    a.) W.R.T. run time of your game, are you trying to login with the same playfab account that you logged into the editor with? The login with editor extensions is different than the accounts (per title id) in game manager
    b.) W.R.T. run time, are you setting the appropriate "CreateAccount" setting on the LoginRequest object on the accounts first login call?

2.) sometimes when I open up the PlayFab Editor Extension window
    a.) W.R.T. the Unity Editor mode, would this be something you toggle between ediotr windows with? (I'm seeing this callstack step lines go through our menu draw, are you closing/opening the window frequently? Or would I be able to trigger this by swapping between an editor window's tabs?)

**Comment by fredsome** [comment]
I have the same problem.

**Comment by Hugodzl** [comment]
Hi Todd,
Thank you for getting back to me.

1.A: Yes, I use a different account, I use a regular player account that I
created to login to the game and my PlayFab account to login with the
editor extension
1.B: Yes, I do. It also happens with other player accounts and
it's intermittent, it doesn't always happen.

2.A: I used to keep the tab available in the editor, although I usually
kept it toggle off because I didn't need to see its content but yes simply
toggling it on sometimes caused the error. But then I thought maybe that's
what was causing the error, so since then I have removed it from the
available tabs in my editor and if I need it I'll go get it from the
Windows menu option.

Today, I changed my password and when I tried logging in back in the editor
extension, the same error occurred. I verified the password and email.

This project is in a git repository and we are a few developers using it.
We also tried using each of us our own Playfab account in the editor and we
also tried using the same for everyone.

[image: image.png]

Le jeu. 16 juil. 2020 à 20:40, Todd Bello <notifications@github.com> a
écrit :

**Comment by toddbellMSFT** [comment]
This issue looks similar to the reply at the end of this forum post: https://community.playfab.com/questions/13637/unity-editorextension-caught-and-error-invalid-jso.html 

To get higher visibility for this issue, I'd recommend posting in the forum in the future. Our GitHub Issues are not monitored as closely as our developer forums.

Walking the callstack again in this post, I noticed OnSharedErrorCallback may be triggered by some odd logic with 2 Factor Authentication. 

Do you have 2 factor auth enabled on your playfab account?

**Comment by fredsome** [comment]
How can i see those factor on my playfab account?

**Comment by toddbellMSFT** [comment]
If you log in to playfab.com or on the editor extensions, you should see a pop up for 2FA. 

The setting should be visible from https://developer.playfab.com/en-US/profile/edit after you log in.

**Comment by toddbellMSFT** [comment]
As we have not heard back in awhile, we would like to ask one more time before we close this out. 

Did enabling 2FA fix this issue?

**Comment by fredsome** [comment]
Not really,i think it is a problem from unity’s servers.

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Todd Bello <notifications@github.com>
Envoyé : Monday, September 28, 2020 1:00:15 PM
À : PlayFab/UnityEditorExtensions <UnityEditorExtensions@noreply.github.com>
Cc : Freddy Some <fredsome@hotmail.fr>; Comment <comment@noreply.github.com>
Objet : Re: [PlayFab/UnityEditorExtensions] PlayFab EditorExtensions: Caught an error:Invalid JSON string (#125)


As we have not heard back in awhile, we would like to ask one more time before we close this out.

Did enabling 2FA fix this issue?

**Comment by toddbellMSFT** [comment]
Unity's servers should not be involved in PlayFab's sign in process (either from the unity editor extension or during game runtime). 

Since I cannot replicate this error, can you make a new post about this issue on playfab's developer support forums https://community.playfab.com/index.html and see if others have been able to see something similar?

**Comment by fredsome** [comment]
Ok,no problem

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Todd Bello <notifications@github.com>
Envoyé : Monday, September 28, 2020 4:33:41 PM
À : PlayFab/UnityEditorExtensions <UnityEditorExtensions@noreply.github.com>
Cc : Freddy Some <fredsome@hotmail.fr>; Comment <comment@noreply.github.com>
Objet : Re: [PlayFab/UnityEditorExtensions] PlayFab EditorExtensions: Caught an error:Invalid JSON string (#125)


Unity's servers should not be involved in PlayFab's sign in process (either from the unity editor extension or during game runtime).

Since I cannot replicate this error, can you make a new post about this issue on playfab's developer support forums https://community.playfab.com/index.html and see if others have been able to see something similar?
