### ISSUE TITLE
ENABLE_PLAYFABPLAYSTREAM_API is not listed in the section to enable/disable sdk features

### ISSUE THREAD

**Issue by nlebedenco** [PlayFab/UnityEditorExtensions#84]

**Comment by nlebedenco** [comment]
by "section" I mean the Settings->API tab.

**Comment by pgilmorepf** [comment]
That's a really great catch, I'll fix it right away.

**Comment by pgilmorepf** [comment]
https://github.com/PlayFab/UnityEditorExtensions/pull/87
PlayStream SignalR streaming define is now available, but it's hidden under "ENABLE UNSTABLE FEATURES" toggle, because to be fair... it's not meant to be widely used yet.

I'm going to close this bug, in anticipation of the next release, which will resolve this issue.
