### ISSUE TITLE
Settings->API shows compiler directives unrelated to PlayFab that if unchecked cannot be recovered.

### ISSUE THREAD

**Issue by nlebedenco** [PlayFab/UnityEditorExtensions#86]
Settings->API shows compiler directives unrelated to PlayFab. If unchecked they're removed from the build settings and as consequence disappear from the Extension Window after the editor's hot reload. Now the user must go back to the build settings and re-enter that custom directive again manually. This can be very confusing for the user and produce unintentional/unrealized removal of compiler directives.

**Comment by pgilmorepf** [comment]
That's a really good point.
I mostly added that for the ability to debug what other compiler directives may be present, and to fix my own typos.
Let's brainstorm here:
I'd like to keep something like that functionality, but make it a bit safer.
Unfortunately, due to the fact that the project is immediately rebuilt, I don't have any way of remembering the flag once it is removed.
Do you have any suggestions?

**Comment by nlebedenco** [comment]
Well I agree it would be hard to memorize custom compiler directives, so I'd favor consistency meaning whatever the user can do through a user interface should be potentially undone as well. So simply put I wouldn't touch directives unrelated to PlayFab. Don't even list them or if you do want them listed for whatever reason at least disable the check box making them effectively readonly in the extension GUI. In this case a tooltip could be used to refer new (uninformed) users to the build settings.

**Comment by pgilmorepf** [comment]
I think I've come up with a good compromise.
I've set it so the PlayFab-unrelated flags are only visible when "enable unstable features" is toggled on.
This should mean that most people won't see the flags, in order to accidentally remove them.
It's up for review, and should be submitted today.
https://github.com/PlayFab/UnityEditorExtensions/pull/87
It won't be in an assetbundle until the next build.

**Comment by pgilmorepf** [comment]
I'm going to mark this as done, in anticipation of the next release.
Feel free to reopen the bug if you feel that https://github.com/PlayFab/UnityEditorExtensions/pull/87 doesn't address the issue for you.
