### ISSUE TITLE
Enable Unstable Features what does it do?

### ISSUE THREAD

**Issue by Spartanace1024** [PlayFab/UnityEditorExtensions#94]
Not sure what the Enable Unstable Features toggle actually does. It would be great to get some clarification on this front? Also I've noticed that checking it actually adds packages to the API list that aren't supposed to actually be there.

Check below 
![image](https://user-images.githubusercontent.com/2967721/48502304-0a8f4c80-e7f4-11e8-974e-7d6a4ddbe873.png)

Thanks in advance!

**Comment by pgilmorepf** [comment]
It's a way to hide stuff from you guys, that we don't intend to be fully public yet.
We're migrating away from this system so that experimental code is not deployed in the public SDK but that's not finished yet, so some old experimental code is still visible to you guys.

Basically, you should always leave it off, unless you want to play around with experimental code. (Not supported)
