### ISSUE TITLE
Package should use ASMDEF with 2018.x versions

### ISSUE THREAD

**Issue by gekidoslair** [PlayFab/UnityEditorExtensions#98]
Unity introduced the concept of Assembly definitions a while back - every well-behaved package should be configured and provided with proper asmdef setup. Please update your plugin accordingly.

**Comment by pgilmorepf** [comment]
We will investigate and take appropriate action.
Thanks for reporting this.

**Comment by kamyker** [comment]
For start it would be good to move everything to "Assets/Plugins/" folder. That way scripts are not recompiled if nothing in that folder changed. No idea when it was introduced but it's even in Unity 5.6 docs https://docs.unity3d.com/560/Documentation/Manual/ScriptCompileOrderFolders.html.

Same goes for PlayfabSDK.

**Comment by kamyker** [comment]
Made custom sdk version with this function included:
https://github.com/kamyker/PlayFabUnityEditorExtensions

**Comment by toddbellMSFT** [comment]
Added default generated .asmdef files from Unity Editor to repos here:

https://github.com/PlayFab/UnityEditorExtensions/pull/113 

And 

https://github.com/PlayFab/SDKGenerator/pull/628 

These files will be available in the next SDK publish later this month.

**Comment by kamyker** [comment]
Have you tried building unity project? From what I see It won't work as there are Editor folders that aren't excluded when asmdef is used

**Comment by toddbellMSFT** [comment]
I'm able to build the PlayFab Unity test project with the editor extensions and the sdk with the .asmdef files on 2019.2.9f1 is there an explicit exclusion we should ensure also exists?

**Comment by kamyker** [comment]
Just tried empty project with only edex and I can't build. Edex asmdef has to be setup this way: 
![setup](https://user-images.githubusercontent.com/9093037/70099056-15e72d00-162e-11ea-89f6-825719a63108.png)

Not sure how you are able to build tbh.

**Comment by toddbellMSFT** [comment]
When I generated the asmdef file in unity, by default all platforms were checked. This built. I attempted to uncheck all the platforms since theoretically EditorExtensions would really only matter for the Editor, but I saw that didn't work on my machine initially.

The Unity Documentation does point this issue out, https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html and as a consequence the editor extensions currently become their own assembly definition which would show up as a Player assembly at this moment for CompilationPipeline.

Here's the Editor only platform change: https://github.com/PlayFab/UnityEditorExtensions/pull/114
moving it to under the Editor folder: https://github.com/PlayFab/UnityEditorExtensions/pull/115

and in the SDK shared Editor folder:
https://github.com/PlayFab/SDKGenerator/pull/629
